### ISSUE TITLE
Add data caching for Avail nft collections

### ISSUE THREAD

**Issue by saltict** [Koniverse/Static-Data-Caching#5]
Create `/data/nfts/avail/collection_id.json` files

**Comment by phonglnDEV** [comment]
Em đã đẩy data của các bộ NFT Avail lên rồi ạ:
- https://static-cache.subwallet.app/nfts/avail/0x0b789bc0ebe0505700c41cec5986948530e59f444c9383b5ff5d6d3daa14cece.json
- https://static-cache.subwallet.app/nfts/avail/0x37b0aaee83e907d445f41f769731cf8f1bc17c2c211cdb47262f6ca220e9f976.json
- https://static-cache.subwallet.app/nfts/avail/0xa3974497d44d0e1e5a06dc6ceb6cae48dcd9ef2a0369e89d01276830096d32d8.json
